### ISSUE TITLE
Halaman Dashboard Masih Belum Responsive

### ISSUE THREAD

**Issue by cattow** [RadyaI/onelink#3]
## Deskripsi
Pada halaman dashboard tampilan pada saat dibuka di device yang memiliki ukuran kecil masih belum responsive
- Masuk ke halaman dashboard
- sidebar tidak bisa ditutup sehingga menghancurkan UI dari halaman dashboard
- desain masih belum mobile friendly 

## Informasi tambahan:
- Browser: Google Chrome
- OS: Android

**Comment by RadyaI** [comment]
Ok ok
